project:
  type: website
  output-dir: docs

website:
  title: Oxford IHTM CodeHub
  site-url: https://oxford-ihtm.io/
  navbar:
    title: false
    background: primary
    logo: https://avatars.githubusercontent.com/u/35218318?s=200&v=4
    logo-alt: Oxford IHTM CodeHub
    tools:
      - icon: twitt
        href: https://twitter.com
      - icon: github
        href: https://github.com/OxfordIHTM
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    center: "Copyright 2024, Oxford IHTM" 
    background: light
    border: false
  reader-mode: true
  repo-url: https://github.com/OxfordIHTM/oxfordihtm.github.io
  repo-actions: [edit, source, issue]
  issue-url: https://github.com/OxfordIHTM/OxfordIHTM.github.io/issues
  
format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual
