project:
  type: website
  output-dir: _site

website:
  title: "Oxford iHealth"
  site-url: https://oxford-ihtm.io
  description: "Fostering innovation, research, and education in the field of computational sciences for health"
  navbar:
    title: false
    background: info
    logo: images/ihealth_base_inline.png
    logo-alt: Oxford iHealth
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/company/oxford-ihealth
      - icon: mastodon
        href: https://mastodon.social/@ihealth
        rel: me
      - icon: github
        href: https://github.com/OxfordIHTM
    left:
      # - href: index.qmd
      #   text: Home
      - text: About
        href: about/index.qmd
      - text: Blog
        href: blog.qmd
      - text: Teaching
        menu:
          - text: Open and Reproducible Science in R
            href: teaching/index.qmd
          - text: Learning Resources
            href: teaching/learning-resources.qmd
      - text: Projects
        menu:
          - text: Champions Programme
            href: champions/index.qmd
      - text: Packages
        href: packages/index.qmd
  page-footer: 
    center: "Copyright 2025, University of Oxford MSc in International Health and Tropical Medicine" 
    background: light
    border: false
  reader-mode: true
  repo-url: https://github.com/OxfordIHTM/OxfordIHTM.github.io
  repo-actions: [edit, issue]
  issue-url: https://github.com/OxfordIHTM/OxfordIHTM.github.io/issues
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-PSJXMNM72F"
    anonymize-ip: true
  
format:
  html:
    theme: journal
    css: styles.css
    toc: true
    highlight-style: breeze
    code-block-bg: true
    