project:
  type: website
  output-dir: _site

website:
  title: Oxford iHealth
  site-url: https://oxford-ihtm.io/
  navbar:
    title: "Oxford iHealth"
    background: primary
    logo: images/ihealth_base_pos.png
    logo-alt: Oxford iHealth
    tools:
      - icon: github
        href: https://github.com/OxfordIHTM
    left:
      - href: index.qmd
        text: Home
      - text: Teaching
        menu:
          - href: open-reproducible-science.qmd
            text: Open Science and Reproducible Research in R
          - href: teaching/resources.qmd
            text: Learning Resources
      - href: projects/index.qmd
        text: Projects
  # sidebar:
  #   logo: images/ihealth_base_pos.png
  #   logo-alt: Oxford iHealth
  page-footer: 
    center: "Copyright 2024, University of Oxford MSc in International Health and Tropical Medicine" 
    background: light
    border: false
  reader-mode: true
  repo-url: https://github.com/OxfordIHTM/oxfordihtm.github.io
  repo-actions: [edit, issue]
  issue-url: https://github.com/OxfordIHTM/OxfordIHTM.github.io/issues
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-PSJXMNM72F"
    anonymize-ip: true
  
format:
  html:
    theme: litera
    css: styles.css
    # grid:
    #   sidebar-width: 250px
    #   body-width: 900px
    #   margin-width: 250px
    #   gutter-width: 1.5rem
    toc: true
