---
title: "Resources"
---

## Specific resources for the module

Here is a quick guide of the various learning resources produced and/or managed by the course/module that are available to IHTM students and alumni.

* [Oxford IHTM CodeHub Handbook](https://oxford-ihtm.io/handbook)

This handbook provides detailed guides to common and frequently asked questions regarding tools, techniques, and workarounds that we use/implement when using R, RStudio, and git. This handbook is not a guide for writing code but a guide to using the R, RStudio, and git toolkit.

* [Open Science and Reproducible Research in R module website](https://oxford-ihtm.io/open-reproducible-science)

This is the module webpage that is the go to page to access the teaching materials for the module. In this site, the module sessions are listed out with their description, recommended and suggested readings, and links to the their online session slides, PDF version of the session slides, and R script that generates the slides (even the module slides are reproducible!). These information are also available on Canvas but it is recommended that this webpage be your go to portal for module information as it is updated immediately as needed before any updates make their way to Canvas.

* [Practical R for Epidemiologists](https://practical-r.org)

This is our main guide to knowing how to use R for statistical and epidemiological purposes. This is the resource that will show and help you how to code in R.

* [Oxford IHTM CodeHub GitHub organisation account](https://github.com/OxfordIHTM)

This is the Oxford IHTM CodeHub GitHub organisation. If you have gone through the pre-arrival technology setup session, you would have been guided to making your GitHub account and you would have been invited to be a member of the Oxford IHTM CodeHub GitHub organisation. If you don't remember doing so, please check the email account you used to register for GitHub for an email inviting you to the Oxford IHTM CodeHub organisation.

* GitHub Classroom

We will be using GitHub Classroom to distribute homework/classwork that we will be working on in class. You don't have to do anything other than to have a GitHub account and to open the links sent to you to accept the GitHub Classroom assignments. When accepting your first assignment, you will automatically be included into the Oxford IHTM CodeHub student roster.

* [Oxford IHTM CodeHub GitHub Discussion](https://github.com/orgs/OxfordIHTM/discussions)

This is the Oxford IHTM CodeHub discussion forum. The idea for this is to serve as a forum not only for the current class but also for the alumni of the course who have gone through the module. The main use case for this discussion board is for current and previous students to raise R-related questions (either on code and/or the toolkit). This way, fellow members can potentially provide answers and discuss. The discussion board allows for these to be made available to all members and potentially learn from them.

## General resources

