on:
  pull_request:
    branches: main

name: test-website

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MAPBOX_PUBLIC_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
      MAPBOX_SECRET_TOKEN: ${{ secrets.MAPBOX_SECRET_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          imagemagick libmagick++-dev gsfonts libcurl4-openssl-dev \
          libssl-dev libgdal-dev gdal-bin libgeos-dev libproj-dev \
          libsqlite3-dev libssl-dev libudunits2-dev libprotobuf-dev \
          protobuf-compiler
                  
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          